### PR TITLE
Add S3Boto3 Storage Checks

### PR DESCRIPTION
**Pull request by carderm**
Added S3Boto3 Storage checks as this is the recommended way to access S3 now.

### CODE REVIEW

**Comment by codingjoe** [comment]
Hi @carderm, thanks for the patch. Can you elaborate a bit more about what it is you are trying to accomplish?

Thx!
-Joe

**Comment by carderm** [comment]
Hi - the current S3 Health Check uses S3Boto Storage to check for S3. 
This modification adds the new storage class of S3Boto3 (note the 3 on the end - not my naming convention!) As I am using this new storage class, the current health check failed without this update. 

The quote from django-storages is:  

> "It is highly recommended that all new projects (at least) use the boto3 backend since it has many bug fixes and performance improvements over boto and is the future; boto is lightly maintained if at all."

[django-storages](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#usage)

Thanks!

**Comment by codingjoe** [comment]
Hi carderm, I don't see where the current health check uses S3Boto. It actually uses whatever is defined as a default storage in you settings.
https://github.com/KristianOellegaard/django-health-check/blob/da267a54f80b74d0710e82f7650c4c9b8293d7ee/health_check/storage/backends.py#L77

**Comment by codingjoe** [comment]
Please correct me if I'm wrong, maybe I am missing something.

**Comment by carderm** [comment]
Hi - I'm not talking about the default file storage, but the S3 Storage used on AWS (Amazon Web Services).

The line which references the old S3 Boto is here:
[`S3Boto Storage:`](https://github.com/KristianOellegaard/django-health-check/blob/da267a54f80b74d0710e82f7650c4c9b8293d7ee/health_check/contrib/s3boto_storage/backends.py#L20)

**Comment by codingjoe** [comment]
@carderm sorry, my bad 👍 
For some reason the tests didn't run on your last commits. Can you maybe rebase you commits for travis to run the test suite. I would also encourage you to add a test for you backend if possible.

**Comment by codingjoe** [comment]
@carderm, are you still with us?

**Comment by carderm** [comment]
Hi - yes I'll take a look asap. been super busy!

**Comment by codingjoe** [comment]
Cool! Looking forward!

**Comment by codingjoe** [comment]
@carderm can you ticket the little checkmark to the left, that allows me to edit your PR?

**Comment by carderm** [comment]
Hi - you should be able to edit this? let me know which setting needs changing if not?

**Comment by codingjoe** [comment]
Released in [3.1.0](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.1.0)

**Pull request closed without merging**
