### PR TITLE
Fix `default_app_config` `RemovedInDjango41Warning` warning

### LINKED ISSUE #308: Django 4.1 deprecation warning
Hi there!

I just saw a deprecation warning for a future django version. Maybe you could fix it?

> RemovedInDjango41Warning: 'health_check.db' defines default_app_config = 'health_check.db.apps.HealthCheckConfig'. Django now detects this configuration automatically. You can remove default_app_config.

> RemovedInDjango41Warning: 'health_check.cache' defines default_app_config = 'health_check.cache.apps.HealthCheckConfig'. Django now detects this configuration automatically. You can remove default_app_config.

Thx!
Ronny

### PR DESCRIPTION
**Pull request by meteozond**
Fixes #308

### CODE REVIEW

**Comment by federicosilvestri** [comment]
Plz merge this pull request...

**Review by gdalmau — APPROVED** [review]

**Comment by gdalmau** [comment]
@meteozond Please link https://github.com/KristianOellegaard/django-health-check/issues/308 to be closed in the description

**Comment by meteozond** [comment]
@gdalmau, what do you mean? Your comment is already linking it, isn't it?

**Comment by gdalmau** [comment]
@meteozond I meant what you wrote now in the description, `Fixes #308` so when this PR gets merged the issue gets closed :)

**Comment by KOliver94** [comment]
Thanks @meteozond for this PR, I needed this as well. @gdalmau I guess the description got updated. Could you please merge it?

**Comment by gdalmau** [comment]
> Thanks @meteozond for this PR, I needed this as well. @gdalmau I guess the description got updated. Could you please merge it?

I'm not a contributor of this repository, hopefully @KristianOellegaard will give some feedback

**Pull request merged**
