### PR TITLE
Test against more Django and Python versions

### PR DESCRIPTION
**Pull request by JayH5**
* Test against Django 2.1 & 2.2
* Install Django in tox environment from package rather than git archive
* Update default Python version in Travis to 3.7
* Test against all supported versions of Python for latest Django LTS release
* Slight Travis file cleanup (move matrix things all to one place, `jobs` is an alias for `matrix`)

This is a large-ish change to the Travis file I've made without any consultation, so I'd be totally OK if you wanted me to make fewer changes or to pick out some of these changes yourself.

### CODE REVIEW

**Comment by codingjoe** [comment]
@JayH5 thanks for the contribution. Good idea, I didn't know that we haven't updated the test suite in so long. Please drop 1.11, since 2.2 is a new LTS. I will issue a new major release dropping 1.11 support.
I am a bit confused, that you didn't run the test suite in all Python version. Is there any particular reason. It would seem plausible to me, to use the Django/Python version combinations that are actually supported by Django.

**Comment by JayH5** [comment]
@codingjoe 
> Please drop 1.11, since 2.2 is a new LTS. I will issue a new major release dropping 1.11 support.

Done.

> I am a bit confused, that you didn't run the test suite in all Python version. Is there any particular reason.

Just didn't want to create too many build jobs. Since this is now only tested against two Django versions, testing against all supported Python versions definitely makes sense.

**Review by codingjoe — APPROVED** [review]
LGTM, you just need to resolve the conflicts. Thx!

**Comment by ntravis** [comment]
@JayH5 nudge to resolve conflicts and a 👍 for the work

**Comment by codingjoe** [comment]
I will close this one, since its outdated. We already test the current master against, Py37 and Django 2.2.

**Pull request closed without merging**
