### PR TITLE
Improve Python 2.7 compatibility by adding explicit coding to project files

### PR DESCRIPTION
**Pull request by aleksihakli**
This patchset adds unicode coding tags for better Python 2 compatibility.

### CODE REVIEW

**Review by codingjoe — DISMISSED** [review]
It's not really needed, since there are no none ASCII characters in those files, but just to be safe it's a good idea.

**Review by codingjoe — CHANGES_REQUESTED** [review]
Please drop the second commit. It has nothing to do with Python 2 support and actually removes support for all Django versions prior to the App loading change in Dajngo 1.7

**Comment by codingjoe** [comment]
@aleksihakli we can talk about removing the old `models.py` files. But that is a breaking chance and would require at least a new major release and some documentation.
I guess we can do this at a later point.

**Comment by aleksihakli** [comment]
Updated PR as per request.

**Comment by codingjoe** [comment]
Released in 1.2.1

**Pull request closed without merging**
