### PR TITLE
Added tests for plugins

### PR DESCRIPTION
**Pull request by aleksihakli**
Fixes and help for PR #49 that @mspeedy kindly contributed.

- Add Celery to requirements-dev.txt
- Sort import statements
- Fix counting stock plugin modules in test_autodiscover
- Fixes to Python 2 and 3 compatibility
- Fixes to inherited class initialization semantics (add calls to base classes in `__init__` methods). For some reason QuantifiedCode is still not happy with the Python 2 compatible initialization syntax and suggests just calling `super().__init__`, which we can't do while supporting Python 2 (unless done with [future](http://python-future.org/overview.html) super which would add a dependency).

### CODE REVIEW

**Comment by aleksihakli** [comment]
@mspeedy @codingjoe this PR should fix testing problems with #49 and be a smooth merger.

**Comment by mspeedy** [comment]
Looks good, thank you for the help!

**Comment by codingjoe** [comment]
@mspeedy @aleksihakli cool, but who's implementing review changes now?


Anyways, this is pretty cool, but I don't like that it changes existing tests and transforms everything to `UnitTest` where we used `py.test`. I personally perfer pytest, but I appreciate everyone how takes the time to write a test. Pytest allows executing both UnitTests and pytest. Therefore it's fine if the new tests are written `UnitTest` style, but please don't change the old once.

**Review by codingjoe — CHANGES_REQUESTED** [review]
Please dont' change existing tests

**Comment by aleksihakli** [comment]
I thought to help since @mspeedy said he doesn't have time to do all the updates.

I'll roll back the test migrations from object inherited tests to TestCases and rebase this on top of the current master.

**Comment by aleksihakli** [comment]
On closer inspection the commit chain is broken and inclues and then deletes 600kloc of libraries. I'll open another pull request with those additions and removals squashed and tests done in the original style.

**Pull request closed without merging**
