### PR TITLE
Convert README from Markdown to reStructuredText

### LINKED ISSUE #37: Pypi page looks strange
The pypi page of your project looks strange: https://pypi.python.org/pypi/django-health-check

AFAIK pypi does not support mark-down. You need to use reStructuredText.

### PR DESCRIPTION
**Pull request by aleksihakli**
This patch improves Python package convention conformance by using the preffered RST format instead of Markdown, allowing clean PyPI page display.

Fixes #37

### CODE REVIEW

**Review by codingjoe — APPROVED** [review]
Looks good, thanks!

**Comment by aleksihakli** [comment]
As a closing note, this could probably be released as 1.2.1 to actually fix the PyPI page:

https://pypi.python.org/pypi/django-health-check

**Comment by codingjoe** [comment]
hm... there is nothing wrong with the code, therefore I didn't release it.

**Comment by aleksihakli** [comment]
Yeah I guess it will be released down the road 👍

**Comment by codingjoe** [comment]
@aleksihakli I released your utf-8 commit therefore this is live now 🎉

**Pull request merged**
